//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Cloud.Core.Model.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EngineCloudDataContext : DbContext
    {
        public EngineCloudDataContext()
            : base("name=EngineCloudDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<QueueActionReference> QueueActionReference { get; set; }
        public virtual DbSet<QueueActionStep> QueueActionStep { get; set; }
        public virtual DbSet<ServerBlock> ServerBlock { get; set; }
        public virtual DbSet<QueueAction> QueueAction { get; set; }
        public virtual DbSet<Server> Server { get; set; }
    }
}
