//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Cloud.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Image()
        {
            this.Server = new HashSet<Server>();
        }
    
        public int ImageId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Active { get; set; }
        public int TypeHipervisorId { get; set; }
        public string Password { get; set; }
        public string Plataform { get; set; }
        public string Distribution { get; set; }
        public string Version { get; set; }
        public string Architecture { get; set; }
        public string TypeInstall { get; set; }
        public string Observation { get; set; }
        public Nullable<int> DiskSO { get; set; }
        public Nullable<bool> Internal { get; set; }
        public string AdditionalProducts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Server> Server { get; set; }
    }
}
