//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Cloud.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueActionReference
    {
        public long QueueActionId { get; set; }
        public long ValueId { get; set; }
        public int TypeQueueActionReferenceId { get; set; }
    
        public virtual QueueAction QueueAction { get; set; }
    }
}
