//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Cloud.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QueueAction()
        {
            this.QueueActionStep = new HashSet<QueueActionStep>();
        }
    
        public long QueueActionId { get; set; }
        public Nullable<long> AfterQueueActionId { get; set; }
        public string Name { get; set; }
        public string User { get; set; }
        public Nullable<int> ClientId { get; set; }
        public int TypeActionId { get; set; }
        public int StatusActionId { get; set; }
        public string Result { get; set; }
        public int TotalCompleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string IpAddress { get; set; }
    
        public virtual QueueActionReference QueueActionReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueActionStep> QueueActionStep { get; set; }
    }
}
