//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Cloud.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueActionStep
    {
        public long QueueActionStepId { get; set; }
        public long QueueActionId { get; set; }
        public string Name { get; set; }
        public int TypeActionStepId { get; set; }
        public int StatusActionId { get; set; }
        public string RequestBody { get; set; }
        public string ResultBody { get; set; }
        public string ServiceCode { get; set; }
        public int Attempts { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual QueueAction QueueAction { get; set; }
    }
}
