//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Cloud.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public long ServerId { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string IP { get; set; }
        public int StatusId { get; set; }
        public int StatusBlockId { get; set; }
        public string MessageStatus { get; set; }
        public int ClientId { get; set; }
        public int PlanId { get; set; }
        public int ImageId { get; set; }
        public int TypeManagementId { get; set; }
        public int TypeInstallOriginId { get; set; }
        public string HypervisorIdentifier { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Image Image { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
